version: "3"

services:
  ecrnow-ui:
    image: ecrnow-ui
    container_name: ecrnow-ui
    restart: on-failure
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_ECR_BASE_URL=http://pathways.mitre.org:8081
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
